namespace CTD.Helpers
{
    public class CommonHelper
    {
        private static Dictionary<string, string> ukCitiesDict = null;
        public static Dictionary<string, string> UKCitiesDictionary()
        {
            if (ukCitiesDict is null)
            {
                ukCitiesDict = new()
                {
                    {"Aberdeen", "aberdeen"},
                    {"Armagh", "armagh"},
                    {"Bangor", "bangor"},
                    {"Bath", "bath"},
                    {"Belfast", "belfast"},
                    {"Birmingham", "birmingham"},
                    {"Bradford", "bradford"},
                    {"Brighton", "brighton-and-hove"},
                    {"Bristol", "bristol"},
                    {"Cambridge", "cambridge"},
                    {"Canterbury", "canterbury"},
                    {"Cardiff", "cardiff"},
                    {"Carlisle", "carlisle"},
                    {"Chelmsford", "chelmsford"},
                    {"Chester", "chester"},
                    {"Chichester", "chichester"},
                    {"Colchester", "colchester"},
                    {"Coventry", "coventry"},
                    {"Derby", "derby"},
                    {"Doncaster", "doncaster"},
                    {"Dundee", "dundee"},
                    {"Dunfermline", "dunfermline"},
                    {"Durham", "durham"},
                    {"Edinburgh", "edinburgh"},
                    {"Ely", "ely"},
                    {"Exeter", "exeter"},
                    {"Glasgow", "glasgow"},
                    {"Gloucester", "gloucester"},
                    {"Hereford", "hereford"},
                    {"Inverness", "inverness"},
                    {"Kingston", "kingston-upon-hull"},
                    {"Lancaster", "lancaster"},
                    {"Leeds", "leeds"},
                    {"Leicester", "leicester"},
                    {"Lichfield", "lichfield"},
                    {"Lincoln", "lincoln"},
                    {"Lisburn", "lisburn"},
                    {"Liverpool", "liverpool"},
                    {"London", "london"},
                    {"Londonderry", "londonderry"},
                    {"Manchester", "manchester"},
                    {"Milton Keynes", "milton-keynes"},
                    {"Newcastle", "newcastle-upon-tyne"},
                    {"Newport", "newport"},
                    {"Newry", "newry"},
                    {"Norwich", "norwich"},
                    {"Nottingham", "nottingham"},
                    {"Oxford", "oxford"},
                    {"Perth", "perth"},
                    {"Peterborough", "peterborough"},
                    {"Plymouth", "plymouth"},
                    {"Portsmouth", "portsmouth"},
                    {"Preston", "preston"},
                    {"Ripon", "ripon"},
                    {"Salford", "salford"},
                    {"Salisbury", "salisbury"},
                    {"Sheffield", "sheffield"},
                    {"Southampton", "southampton"},
                    {"Southend", "southend-on-sea"},
                    {"St Albans", "st-albans"},
                    {"St Asaph", "st-asaph-llanelwy"},
                    {"St Davids", "st-davids"},
                    {"Stirling", "stirling"},
                    {"Stoke on Trent", "stoke-on-trent"},
                    {"Sunderland", "sunderland"},
                    {"Swansea", "swansea"},
                    {"Truro", "truro"},
                    {"Wakefield", "wakefield"},
                    {"Wells", "wells"},
                    {"Westminster", "westminster"},
                    {"Winchester", "winchester"},
                    {"Wolver", "wolverhampton"},
                    {"Worcester", "worcester"},
                    {"Wrexham", "wrexham"},
                    {"York", "york" }
                    //{ "Milton Keynes","milton-keynes" },
                    //{ "Leeds","leeds" },
                    //{ "Manchester", "manchester" },
                    //{ "Colchester", "colchester" },
                    //{ "Chester", "chester" },
                    //{ "Armagh", "armagh" },
                    //{ "Lincoln", "lincoln" },
                    //{ "Derby", "derby" },
                    //{ "Bath", "bath" },
                    //{ "Gloucester", "gloucester" },
                    //{ "Durham", "durham" },
                    //{ "Liverpool", "liverpool" },
                    //{ "Bangor", "bangor" },
                    //{ "Dundee", "dundee" },
                    //{ "Exeter", "exeter" },
                    //{ "Brighton", "brighton-and-hove" },
                    //{ "Kingston", "kingston-upon-hull" },
                    //{ "Aberdeen", "aberdeen" },
                    //{ "Birmingham", "birmingham" },
                    //{ "Edinburgh", "edinburgh" },
                    //{ "Lisburn", "lisburn" },
                    //{ "Chelmsford", "chelmsford" },
                    //{ "Lancaster", "lancaster" },
                    //{ "Coventry", "coventry" },
                    //{ "Doncaster", "doncaster" },
                    //{ "Ely", "ely" },
                    //{ "London", "london" },
                    //{ "Belfast", "belfast" },
                    //{ "Cambridge", "cambridge" },
                    //{ "Cardiff", "cardiff" },
                    //{ "Chichester", "chichester" },
                    //{ "Hereford", "hereford" },
                    //{ "Glasgow", "glasgow" },
                    //{ "Bristol", "bristol" },
                    //{ "Bradford", "bradford" },
                    //{ "Canterbury", "canterbury" },
                    //{ "Dunfermline", "dunfermline" },
                    //{ "Londonderry", "londonderry" },
                    //{ "Carlisle", "carlisle" },
                    //{ "Inverness", "inverness" },
                    //{ "Lichfield", "lichfield" },
                    //{ "Oxford", "oxford" }
                };
                ukCitiesDict = ukCitiesDict.OrderBy(x => x.Key).ToDictionary(x => x.Key, x => x.Value);
            }
            return ukCitiesDict;
        }
    }
}
