namespace CTD.Extensions
{
    public static class PortfolioViewsExtensions
    {
        public static string PortfolioViewName(this string source)
        {
            return source switch
            {
                "banner-designs" => "_BannerDesigns",
                "logo-designs" => "_LogoDesigns",
                "social-media-posts-designs" => "_SocialMediaPostsDesigns",
                "web-designs" => "_WebDesigns",
                "c-maxi-seo-and-google-adwords" => "_CMaxiSEOAndGoogleAdword",
                "seo-for-live-training-lab-2" => "_SEOForLiveTrainingLab",
                "ranking-1-blockchain-business-directory-2" => "_RankingNo1BlockchaiBusinesDirectory",
                "beat-competitors-of-a-1-courier-in-seo-2" => "_BeatCompetitorsOfA1CourierInSEO",
                "suninme-org-seo-work-2" => "_SuninmeOrgSEOWork",
                "seo-for-canadian-institute-of-international-business-2" => "_SEOForCanadianInstituteOfInternationalBusiness",
                "website-mobile-app-development-2" => "_WebsiteAndMobileAppDevelopment",
                "web-development-football365" => "_WebDevelopmentForViewsLiveMatches",
                "web-development-for-stainless-steel-railing-kits" => "_WebDevelopmentForStainlessSteelRailingKits",
				"web-development-for-drive-xcel" => "_WebDevelopmentForDriveXcel",
                "web-development-for-flexi-biz-pro" => "_WebDevelopmentForFlexiBizPro",
                "seo-for-admiral-farragut-academy" => "_SEOForAdmiralFarragutAcademy",
                "seo-for-think-up-themes" => "_SEOForThinkUpThemes",
                "seo-for-eiksmarka" => "_SEOForEiksmarka",
                "seo-for-mgbtechnik" => "_SEOForMGbtechnik",
				"app-development-for-aljomah-automative" => "_AppDevAljomahAutomative",
				"app-development-for-dubai-watch-week" => "_AppDevDubaiWatchWeek",
				"app-development-for-pay-box" => "_AppDevPayBox",
				"app-development-for-secret-society" => "_AppDevSecretSociaty",
				"app-development-for-almadallah" => "_AppDevAlmadallah",
				"app-development-for-swim-warrior" => "_AppDevSwimWarrior",
				"app-development-for-up-ticker" => "_AppDevUpTicker",
				"app-development-for-wiki-saleep" => "_AppDevWikiSaleep",
				"web-development-for-news24" => "_WebDevNews24",
				"web-development-for-racing-and-sports" => "_WebDevRacningAndSport",
				"web-development-for-price-match" => "_WebDevPriceMatch",
				"web-development-for-osix-media" => "_WebDevOsixMedia",
				"web-development-for-snl-24-kickoff" => "_WebDevSnl24Kickoff",
				"web-development-for-snl-24-soccer" => "_WebDevSnl24Soccer",
				"web-development-for-tour-planner" => "_WebDevTourPlanner",


				_ => null
            };
        }

        public static string BlogViewName(this string source)
        {
            return source switch
            {
                "define-world-best-it-solution" => "_DefineWorldBestITSolutions",
                "why-blogging-is-important-for-sacramento-seo" => "_BloggingIsImportantForSacramentoSEO",
                _ => null
            };
        }

    }
    public static class ServicesViewsExtensions
    {
        public static string ActionName(this string source)
        {
            return source switch
            {
                "ITStaffAugmentation" => "CitywiseITStaffAugumentation",
                "WebDevelopment" => "CitywiseWebDevelopment",
                "GraphicDesigning" => "CitywiseGraphicDesigning",
                "SEO" => "CitywiseSEO",
                _ => null
            };
        }
        public static string ITStaffServicesViewNameByCity(this string source)
        {
            return source switch
            {
                "aberdeen" => "_ITStaffAugmentationInAberdeen",
                "armagh" => "_ITStaffAugmentationInArmagh",
                "bangor" => "_ITStaffAugmentationInBangor",
                "bath" => "_ITStaffAugmentationInBath",
                "belfast" => "_ITStaffAugmentationInBelfast",
                "birmingham" => "_ITStaffAugmentationInBirmingham",
                "bradford" => "_ITStaffAugmentationInBradford",
                "brighton-and-hove" => "_ITStaffAugmentationInBrightonAndHove",
                "bristol" => "_ITStaffAugmentationInBristol",
                "cambridge" => "_ITStaffAugmentationInCambridge",
                "canterbury" => "_ITStaffAugmentationInCanterbury",
                "cardiff" => "_ITStaffAugmentationInCardiff",
                "carlisle" => "_ITStaffAugmentationInCarlisle",
                "chelmsford" => "_ITStaffAugmentationInChelmsford",
                "chester" => "_ITStaffAugmentationInChester",
                "chichester" => "_ITStaffAugmentationInChichester",
                "colchester" => "_ITStaffAugmentationInColchester",
                "coventry" => "_ITStaffAugmentationInCoventry",
                "derby" => "_ITStaffAugmentationInDerby",
                "doncaster" => "_ITStaffAugmentationInDoncaster",
                "dundee" => "_ITStaffAugmentationInDundee",
                "dunfermline" => "_ITStaffAugmentationInDunfermline",
                "durham" => "_ITStaffAugmentationInDurham",
                "edinburgh" => "_ITStaffAugmentationInEdinburgh",
                "ely" => "_ITStaffAugmentationInEly",
                "exeter" => "_ITStaffAugmentationInExeter",
                "glasgow" => "_ITStaffAugmentationInGlasgow",
                "gloucester" => "_ITStaffAugmentationInGloucester",
                "hereford" => "_ITStaffAugmentationInHereford",
                "inverness" => "_ITStaffAugmentationInInverness",
                "kingston-upon-hull" => "_ITStaffAugmentationInKingstonUponHull",
                "lancaster" => "_ITStaffAugmentationInLancaster",
                "leeds" => "_ITStaffAugmentationInLeeds",
                "leicester" => "_ITStaffAugmentationInLeicester",
                "lichfield" => "_ITStaffAugmentationInLichfield",
                "lincoln" => "_ITStaffAugmentationInLincoln",
                "lisburn" => "_ITStaffAugmentationInLisburn",
                "liverpool" => "_ITStaffAugmentationInLiverpool",
                "london" => "_ITStaffAugmentationInLondon",
                "londonderry" => "_ITStaffAugmentationInLondonderry",
                "manchester" => "_ITStaffAugmentationInManchester",
                "milton-keynes" => "_ITStaffAugmentationInMiltonKeynes",
                "newcastle-upon-tyne" => "_ITStaffAugmentationInNewcastle",
                "newport" => "_ITStaffAugmentationInNewport",
                "newry" => "_ITStaffAugmentationInNewry",
                "norwich" => "_ITStaffAugmentationInNorwich",
                "nottingham" => "_ITStaffAugmentationInNottingham",
                "oxford" => "_ITStaffAugmentationInOxford",
                "perth" => "_ITStaffAugmentationInPerth",
                "peterborough" => "_ITStaffAugmentationInPeterborough",
                "plymouth" => "_ITStaffAugmentationInPlymouth",
                "portsmouth" => "_ITStaffAugmentationInPortsmouth",
                "preston" => "_ITStaffAugmentationInPreston",
                "ripon" => "_ITStaffAugmentationInRipon",
                "salford" => "_ITStaffAugmentationInSalford",
                "salisbury" => "_ITStaffAugmentationInSalisbury",
                "sheffield" => "_ITStaffAugmentationInSheffield",
                "southampton" => "_ITStaffAugmentationInSouthampton",
                "southend-on-sea" => "_ITStaffAugmentationInSouthendOnSea",
                "st-albans" => "_ITStaffAugmentationInStAlbans",
                "st-asaph-llanelwy" => "_ITStaffAugmentationInStAsaph",
                "st-davids" => "_ITStaffAugmentationInStDavids",
                "stirling" => "_ITStaffAugmentationInStirling",
                "stoke-on-trent" => "_ITStaffAugmentationInStokeOnTrent",
                "sunderland" => "_ITStaffAugmentationInSunderland",
                "swansea" => "_ITStaffAugmentationInSwansea",
                "truro" => "_ITStaffAugmentationInTruro",
                "wakefield" => "_ITStaffAugmentationInWakefield",
                "wells" => "_ITStaffAugmentationInWells",
                "westminster" => "_ITStaffAugmentationInWestminster",
                "winchester" => "_ITStaffAugmentationInWinchester",
                "wolverhampton" => "_ITStaffAugmentationInWolverhampton",
                "worcester" => "_ITStaffAugmentationInWorcester",
                "wrexham" => "_ITStaffAugmentationInWrexham",
                "york" => "_ITStaffAugmentationInYork",
                _ => null
            };
        }
        public static string WebDevServicesViewNameByCity(this string source)
        {
            return source switch
            {
                "aberdeen" => "_WebDevelopmentInAberdeen",
                "armagh" => "_WebDevelopmentInArmagh",
                "bangor" => "_WebDevelopmentInBangor",
                "bath" => "_WebDevelopmentInBath",
                "belfast" => "_WebDevelopmentInBelfast",
                "birmingham" => "_WebDevelopmentInBirmingham",
                "bradford" => "_WebDevelopmentInBradford",
                "brighton-and-hove" => "_WebDevelopmentInBrightonAndHove",
                "bristol" => "_WebDevelopmentInBristol",
                "cambridge" => "_WebDevelopmentInCambridge",
                "canterbury" => "_WebDevelopmentInCanterbury",
                "cardiff" => "_WebDevelopmentInCardiff",
                "carlisle" => "_WebDevelopmentInCarlisle",
                "chelmsford" => "_WebDevelopmentInChelmsford",
                "chester" => "_WebDevelopmentInChester",
                "chichester" => "_WebDevelopmentInChichester",
                "colchester" => "_WebDevelopmentInColchester",
                "coventry" => "_WebDevelopmentInCoventry",
                "derby" => "_WebDevelopmentInDerby",
                "doncaster" => "_WebDevelopmentInDoncaster",
                "dundee" => "_WebDevelopmentInDundee",
                "dunfermline" => "_WebDevelopmentInDunfermline",
                "durham" => "_WebDevelopmentInDurham",
                "edinburgh" => "_WebDevelopmentInEdinburgh",
                "ely" => "_WebDevelopmentInEly",
                "exeter" => "_WebDevelopmentInExeter",
                "glasgow" => "_WebDevelopmentInGlasgow",
                "gloucester" => "_WebDevelopmentInGloucester",
                "hereford" => "_WebDevelopmentInHereford",
                "inverness" => "_WebDevelopmentInInverness",
                "kingston-upon-hull" => "_WebDevelopmentInKingstonUponHull",
                "lancaster" => "_WebDevelopmentInLancaster",
                "leeds" => "_WebDevelopmentInLeeds",
                "leicester" => "_WebDevelopmentInLeicester",
                "lichfield" => "_WebDevelopmentInLichfield",
                "lincoln" => "_WebDevelopmentInLincoln",
                "lisburn" => "_WebDevelopmentInLisburn",
                "liverpool" => "_WebDevelopmentInLiverpool",
                "london" => "_WebDevelopmentInLondon",
                "londonderry" => "_WebDevelopmentInLondonderry",
                "manchester" => "_WebDevelopmentInManchester",
                "milton-keynes" => "_WebDevelopmentInMiltonKeynes",
                "newcastle-upon-tyne" => "_WebDevelopmentInNewcastle",
                "newport" => "_WebDevelopmentInNewport",
                "newry" => "_WebDevelopmentInNewry",
                "norwich" => "_WebDevelopmentInNorwich",
                "nottingham" => "_WebDevelopmentInNottingham",
                "oxford" => "_WebDevelopmentInOxford",
                "perth" => "_WebDevelopmentInPerth",
                "peterborough" => "_WebDevelopmentInPeterborough",
                "plymouth" => "_WebDevelopmentInPlymouth",
                "portsmouth" => "_WebDevelopmentInPortsmouth",
                "preston" => "_WebDevelopmentInPreston",
                "ripon" => "_WebDevelopmentInRipon",
                "salford" => "_WebDevelopmentInSalford",
                "salisbury" => "_WebDevelopmentInSalisbury",
                "sheffield" => "_WebDevelopmentInSheffield",
                "southampton" => "_WebDevelopmentInSouthampton",
                "southend-on-sea" => "_WebDevelopmentInSouthendOnSea",
                "st-albans" => "_WebDevelopmentInStAlbans",
                "st-asaph-llanelwy" => "_WebDevelopmentInStAsaph",
                "st-davids" => "_WebDevelopmentInStDavids",
                "stirling" => "_WebDevelopmentInStirling",
                "stoke-on-trent" => "_WebDevelopmentInStokeOnTrent",
                "sunderland" => "_WebDevelopmentInSunderland",
                "swansea" => "_WebDevelopmentInSwansea",
                "truro" => "_WebDevelopmentInTruro",
                "wakefield" => "_WebDevelopmentInWakefield",
                "wells" => "_WebDevelopmentInWells",
                "westminster" => "_WebDevelopmentInWestminster",
                "winchester" => "_WebDevelopmentInWinchester",
                "wolverhampton" => "_WebDevelopmentInWolverhampton",
                "worcester" => "_WebDevelopmentInWorcester",
                "wrexham" => "_WebDevelopmentInWrexham",
                "york" => "_WebDevelopmentInYork",


                //"oxford" => "_WebDevelopmentInOxford",
                //"milton-keynes" => "_WebDevelopmentInMiltonKeynes",
                //"bristol" => "_WebDevelopmentInBristol",


                _ => null
            };
        }
        public static string GraphicDesigningServicesViewNameByCity(this string source)
        {
            return source switch
            {
                "aberdeen" => "_GraphicDesigningInAberdeen",
                "armagh" => "_GraphicDesigningInArmagh",
                "bangor" => "_GraphicDesigningInBangor",
                "bath" => "_GraphicDesigningInBath",
                "belfast" => "_GraphicDesigningInBelfast",
                "birmingham" => "_GraphicDesigningInBirmingham",
                "bradford" => "_GraphicDesigningInBradford",
                "brighton-and-hove" => "_GraphicDesigningInBrightonAndHove",
                "bristol" => "_GraphicDesigningInBristol",
                "cambridge" => "_GraphicDesigningInCambridge",
                "canterbury" => "_GraphicDesigningInCanterbury",
                "cardiff" => "_GraphicDesigningInCardiff",
                "carlisle" => "_GraphicDesigningInCarlisle",
                "chelmsford" => "_GraphicDesigningInChelmsford",
                "chester" => "_GraphicDesigningInChester",
                "chichester" => "_GraphicDesigningInChichester",
                "colchester" => "_GraphicDesigningInColchester",
                "coventry" => "_GraphicDesigningInCoventry",
                "derby" => "_GraphicDesigningInDerby",
                "doncaster" => "_GraphicDesigningInDoncaster",
                "dundee" => "_GraphicDesigningInDundee",
                "dunfermline" => "_GraphicDesigningInDunfermline",
                "durham" => "_GraphicDesigningInDurham",
                "edinburgh" => "_GraphicDesigningInEdinburgh",
                "ely" => "_GraphicDesigningInEly",
                "exeter" => "_GraphicDesigningInExeter",
                "glasgow" => "_GraphicDesigningInGlasgow",
                "gloucester" => "_GraphicDesigningInGloucester",
                "hereford" => "_GraphicDesigningInHereford",
                "inverness" => "_GraphicDesigningInInverness",
                "kingston-upon-hull" => "_GraphicDesigningInKingstonUponHull",
                "lancaster" => "_GraphicDesigningInLancaster",
                "leeds" => "_GraphicDesigningInLeeds",
                "leicester" => "_GraphicDesigningInLeicester",
                "lichfield" => "_GraphicDesigningInLichfield",
                "lincoln" => "_GraphicDesigningInLincoln",
                "lisburn" => "_GraphicDesigningInLisburn",
                "liverpool" => "_GraphicDesigningInLiverpool",
                "london" => "_GraphicDesigningInLondon",
                "londonderry" => "_GraphicDesigningInLondonderry",
                "manchester" => "_GraphicDesigningInManchester",
                "milton-keynes" => "_GraphicDesigningInMiltonKeynes",
                "newcastle-upon-tyne" => "_GraphicDesigningInNewcastle",
                "newport" => "_GraphicDesigningInNewport",
                "newry" => "_GraphicDesigningInNewry",
                "norwich" => "_GraphicDesigningInNorwich",
                "nottingham" => "_GraphicDesigningInNottingham",
                "oxford" => "_GraphicDesigningInOxford",
                "perth" => "_GraphicDesigningInPerth",
                "peterborough" => "_GraphicDesigningInPeterborough",
                "plymouth" => "_GraphicDesigningInPlymouth",
                "portsmouth" => "_GraphicDesigningInPortsmouth",
                "preston" => "_GraphicDesigningInPreston",
                "ripon" => "_GraphicDesigningInRipon",
                "salford" => "_GraphicDesigningInSalford",
                "salisbury" => "_GraphicDesigningInSalisbury",
                "sheffield" => "_GraphicDesigningInSheffield",
                "southampton" => "_GraphicDesigningInSouthampton",
                "southend-on-sea" => "_GraphicDesigningInSouthendOnSea",
                "st-albans" => "_GraphicDesigningInStAlbans",
                "st-asaph-llanelwy" => "_GraphicDesigningInStAsaph",
                "st-davids" => "_GraphicDesigningInStDavids",
                "stirling" => "_GraphicDesigningInStirling",
                "stoke-on-trent" => "_GraphicDesigningInStokeOnTrent",
                "sunderland" => "_GraphicDesigningInSunderland",
                "swansea" => "_GraphicDesigningInSwansea",
                "truro" => "_GraphicDesigningInTruro",
                "wakefield" => "_GraphicDesigningInWakefield",
                "wells" => "_GraphicDesigningInWells",
                "westminster" => "_GraphicDesigningInWestminster",
                "winchester" => "_GraphicDesigningInWinchester",
                "wolverhampton" => "_GraphicDesigningInWolverhampton",
                "worcester" => "_GraphicDesigningInWorcester",
                "wrexham" => "_GraphicDesigningInWrexham",
                "york" => "_GraphicDesigningInYork",

                _ => null
            };
        }
        public static string SEOServicesViewNameByCity(this string source)
        {
            return source switch
            {
                "aberdeen" => "_SEOInAberdeen",
                "armagh" => "_SEOInArmagh",
                "bangor" => "_SEOInBangor",
                "bath" => "_SEOInBath",
                "belfast" => "_SEOInBelfast",
                "birmingham" => "_SEOInBirmingham",
                "bradford" => "_SEOInBradford",
                "brighton-and-hove" => "_SEOInBrightonAndHove",
                "bristol" => "_SEOInBristol",
                "cambridge" => "_SEOInCambridge",
                "canterbury" => "_SEOInCanterbury",
                "cardiff" => "_SEOInCardiff",
                "carlisle" => "_SEOInCarlisle",
                "chelmsford" => "_SEOInChelmsford",
                "chester" => "_SEOInChester",
                "chichester" => "_SEOInChichester",
                "colchester" => "_SEOInColchester",
                "coventry" => "_SEOInCoventry",
                "derby" => "_SEOInDerby",
                "doncaster" => "_SEOInDoncaster",
                "dundee" => "_SEOInDundee",
                "dunfermline" => "_SEOInDunfermline",
                "durham" => "_SEOInDurham",
                "edinburgh" => "_SEOInEdinburgh",
                "ely" => "_SEOInEly",
                "exeter" => "_SEOInExeter",
                "glasgow" => "_SEOInGlasgow",
                "gloucester" => "_SEOInGloucester",
                "hereford" => "_SEOInHereford",
                "inverness" => "_SEOInInverness",
                "kingston-upon-hull" => "_SEOInKingstonUponHull",
                "lancaster" => "_SEOInLancaster",
                "leeds" => "_SEOInLeeds",
                "leicester" => "_SEOInLeicester",
                "lichfield" => "_SEOInLichfield",
                "lincoln" => "_SEOInLincoln",
                "lisburn" => "_SEOInLisburn",
                "liverpool" => "_SEOInLiverpool",
                "london" => "_SEOInLondon",
                "londonderry" => "_SEOInLondonderry",
                "manchester" => "_SEOInManchester",
                "milton-keynes" => "_SEOInMiltonKeynes",
                "newcastle-upon-tyne" => "_SEOInNewcastle",
                "newport" => "_SEOInNewport",
                "newry" => "_SEOInNewry",
                "norwich" => "_SEOInNorwich",
                "nottingham" => "_SEOInNottingham",
                "oxford" => "_SEOInOxford",
                "perth" => "_SEOInPerth",
                "peterborough" => "_SEOInPeterborough",
                "plymouth" => "_SEOInPlymouth",
                "portsmouth" => "_SEOInPortsmouth",
                "preston" => "_SEOInPreston",
                "ripon" => "_SEOInRipon",
                "salford" => "_SEOInSalford",
                "salisbury" => "_SEOInSalisbury",
                "sheffield" => "_SEOInSheffield",
                "southampton" => "_SEOInSouthampton",
                "southend-on-sea" => "_SEOInSouthendOnSea",
                "st-albans" => "_SEOInStAlbans",
                "st-asaph-llanelwy" => "_SEOInStAsaph",
                "st-davids" => "_SEOInStDavids",
                "stirling" => "_SEOInStirling",
                "stoke-on-trent" => "_SEOInStokeOnTrent",
                "sunderland" => "_SEOInSunderland",
                "swansea" => "_SEOInSwansea",
                "truro" => "_SEOInTruro",
                "wakefield" => "_SEOInWakefield",
                "wells" => "_SEOInWells",
                "westminster" => "_SEOInWestminster",
                "winchester" => "_SEOInWinchester",
                "wolverhampton" => "_SEOInWolverhampton",
                "worcester" => "_SEOInWorcester",
                "wrexham" => "_SEOInWrexham",
                "york" => "_SEOInYork",

                _ => null
            };
        }
    }
}
